---
# This Playbook test if all defined containers can be reached via ansible
# Run nspawn-containers-create.yml before to create them 
- name: Test containers
  hosts: all_containers
  gather_facts: false
  become: true
  tasks:
    - name: Ping the container itself
      ping:
    - name: Test connectivity to container
      command: "ping -c 1 {{ physical_host }}"
      register: machinectl_ping
      retries: 3
      delay: 3
      until: machinectl_ping is success
      delegate_to: "{{ physical_host }}"
      tags:
        - skip_ansible_lint

    - name: Test connectivity to internet via IPv4
      command: "ping -4 -c 1 {{ physical_host }}"
      register: machinectl_ping
      retries: 3
      delay: 3
      until: machinectl_ping is success
      tags:
        - skip_ansible_lint

    - name: Test connectivity to internet via IPv6
      command: "ping -6 -c 1 {{ physical_host }}"
      register: machinectl_ping
      retries: 3
      delay: 1
      until: machinectl_ping is success
      tags:
        - skip_ansible_lint
