---
# This playbook removes and recreates three example containers 
- name: Gather host facts
  hosts: physical_testhost
  gather_facts: true

- name: (Re-) create example container(s)
  hosts: all_containers
  gather_facts: false
  become: true

  # These pretasks will remove the containers
  pre_tasks:
    - name: Get container status
      command: machinectl status "{{ inventory_hostname }}"
      register: machinectl_container_status
      failed_when: false
      changed_when: false
      delegate_to: "{{ physical_host }}"

    - name: Get container image status
      command: machinectl image-status "{{ inventory_hostname }}"
      register: machinectl_container_image_status
      failed_when: false
      changed_when: false
      delegate_to: "{{ physical_host }}"

    - name: Poweroff container
      command: "machinectl poweroff {{ inventory_hostname }}"
      register: machinectl_poweroff
      retries: 3
      delay: 2
      until: machinectl_poweroff is success
      delegate_to: "{{ physical_host }}"
      failed_when: false
      when:
        - machinectl_container_status.rc == 0
      tags:
        - skip_ansible_lint

    - name: Remove container
      command: "machinectl remove {{ inventory_hostname }}"
      register: machinectl_remove
      retries: 3
      delay: 2
      until: machinectl_remove is success
      delegate_to: "{{ physical_host }}"
      failed_when: false
      when:
        - machinectl_container_image_status.rc == 0
      tags:
        - skip_ansible_lint

  # the actual work happens in the role and uses the values from host_vars
  roles:
    - role: "ansible-nspawn-create"
